### ISSUE TITLE
Which qmp command can I use to add hotplug-disk?

### ISSUE THREAD

**Issue by gurugio** [arcnmx/qapi-rs#14]
I tried below code to add a hotplug disk.
It failed with ` Err(Qapi(Error { class: GenericError, desc: "Cannot find device='/home/gkim/work/qmon/testfile' nor node-name='/home/gkim/work/qmon/testfile'", id: None }))` error.

Did I use a wrong command?
If so, could you please inform me which command I should use?

```
           let err_add = stream.execute(qmp::blockdev_add(qmp::BlockdevOptions::raw {
                base: qmp::BlockdevOptionsBase {
                    detect_zeroes: None,
                    cache: None,
                    discard: None,
                    force_share: None,
                    auto_read_only: None,
                    node_name: Some("drive-virtio-disk6".to_string()),
                    read_only: None,
                },
                raw: qmp::BlockdevOptionsRaw {
                    base: qmp::BlockdevOptionsGenericFormat {
                        file: qmp::BlockdevRef::reference(
                            "/home/gkim/work/qmon/testfile".to_string(),
                        ),
                    },
                    size: None,
                    offset: None,
                },
            }),
        )
        .await;
        if err_add.is_err() {
            error!("blockdev_add failed: {:?}", err_add);
            return Ok(());
        }
```

**Comment by arcnmx** [comment]
This is something you should probably ask qemu folks about, I haven't done this outside of the commandline personally. If I had to guess, the problem is that you're using a `reference` when what you actually want is:

```rust
qmp::BlockdevOptionsGenericFormat {
  file: BlockdevRef::definition(Box::new(BlockdevOptions::file {
    file: BlockdevOptionsFile {
      filename: "/home/gkim/work/qmon/testfile".to_string(),
    },
  },
}
```

Alternatively, you could probably `blockdev_add` the `BlockdevOptions::file` separately with its own id, then use that id in the reference. Essentially, you need two blockdevs to do this, not one.

**Comment by gurugio** [comment]
I am sorry that I cannot understand your reply.

I used to use below commands for hotplug a disk.
```
{'execute':'human-monitor-command','arguments':{'command-line':'object_add iothread,id=iothread8'}}
{'execute':'human-monitor-command','arguments':{'command-line':'drive_add 8 file=/dev/nullb0,if=none,id=drive-virtio-disk8,format=raw,snapshot=off,aio=native,cache=none'}}
{'execute':'human-monitor-command','arguments':{'command-line':'device_add virtio-blk-pci,bus=pci.0,addr=0x8,drive=drive-virtio-disk8,iothread=iothread8,num-queues=2,id=virtio-disk8'}}
```

They are NOT QMP commands but HMP(Human Monitor Protocol?) command.
I thought qmp::blockdev_add{} command does drive_add command.
The device_add should be done by qmp::device_add{}.

So you mean I need to call blockdev_add twice, one for the filename and one for the id, do you?

**Comment by gurugio** [comment]
I just found out that there is human-monitor-command.
I succeeded to hot-plug a disk with it.

Thank you very much.
