### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by danobi** [arcnmx/qapi-rs#21]
Hi! Any chance you could cut a new release for the qemu v8.1 changes? I'm looking to use the v8.1 support for https://github.com/danobi/vmtest/pull/28

**Comment by arcnmx** [comment]
Yeah sorry I've been busy this weekend but will get a release out in the next day or two

**Comment by danobi** [comment]
Thank you!

**Comment by arcnmx** [comment]
This should be up now!
